#!/usr/bin/env python3
"""Checks that the board's digit tiles match the TILE_NUM* constants.

The number tiles at the head of the board tileset are the digits 1..8 in
natural order, each in its classic minesweeper colour, generated by
tools/make_tiles.py. render.c picks the tile for an adjacent-mine count through
the TILE_NUM* constants in src/zealmine.h, so each constant must point at the
tile that actually shows its digit. The check reads the built tileset and
asserts that the tile TILE_NUMk carries a digit k glyph in digit k's colour
(segments present, bars the digit must not have absent); any mis-pairing (such
as TILE_NUM2 and TILE_NUM3 being swapped, or a 5 that reads as a 4) fails the
build.
"""

import argparse
import os
import re
import struct
import sys

# Classic minesweeper colours for the digits 1..8, as in tools/make_tiles.py.
DIGIT_RGB = {
    1: (0, 0, 255),
    2: (0, 128, 0),
    3: (255, 0, 0),
    4: (0, 0, 128),
    5: (128, 0, 0),
    6: (0, 128, 128),
    7: (0, 0, 0),
    8: (128, 128, 128),
}

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from gif2tiles import lz77_decompress

TS = 16
DIGITS = (1, 2, 3, 4, 5, 6, 7, 8)
MIN_PIXELS = 8


def rgb565(rgb):
    r, g, b = rgb
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def read_constants(header):
    values = {}
    for m in re.finditer(r"#define\s+TILE_NUM(\d)\s+(\d+)", header):
        values[int(m.group(1))] = int(m.group(2))
    return values


def longest_horizontal_run(tile, lo, hi, target):
    """Longest run of pixels of `target` colour over rows lo..hi, in pixels."""
    best = 0
    for y in range(lo, hi + 1):
        row = tile[y * TS : (y + 1) * TS]
        cur = 0
        for px in row:
            if px == target:
                cur += 1
                best = max(best, cur)
            else:
                cur = 0
    return best


def check_shape(tile, digit, expected):
    """Verifies the tile really shows the digit: every 7-segment sweep that
    makes up the shape is present in the expected colour, and bars the digit
    must not have are absent. Digits 4 and 5 differ exactly by their top and
    bottom bars, which is where the ambiguity used to come from."""
    from make_tiles import SEGMENTS, SEG_GEOM

    absent = set("abcdefg") - set(SEGMENTS[str(digit)])
    for seg in SEGMENTS[str(digit)]:
        x0, y0, x1, y1 = SEG_GEOM[seg]
        sx = (x0 + x1) // 2
        sy = (y0 + y1) // 2
        if tile[sy * TS + sx] != expected:
            return "segment %s of digit %d missing" % (seg, digit)
    missing_bars = ["a", "d"]  # top and bottom bars
    for seg in absent:
        if seg in missing_bars:
            lo = {"a": 2, "d": 11}[seg]
            run = longest_horizontal_run(tile, lo, lo + 3, expected)
            if run >= 6:
                return "digit %d has a %s bar it must not have" % (digit, seg)
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--zts", required=True)
    ap.add_argument("--ztp", required=True)
    ap.add_argument("--header", required=True)
    args = ap.parse_args()

    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

    constants = read_constants(open(args.header).read())
    missing = [k for k in DIGITS if k not in constants]
    if missing:
        sys.exit("TILE_NUM constants for digits %s not found" % missing)
    if sorted(constants.values()) != list(range(8)):
        sys.exit("TILE_NUM constants must point at tiles 0..7 once each")

    raw = lz77_decompress(open(args.zts, "rb").read())
    pal = open(args.ztp, "rb").read()
    pal565 = [struct.unpack("<H", pal[i * 2 : i * 2 + 2])[0] for i in range(256)]

    ok = True
    for digit in DIGITS:
        index = constants[digit]
        tile = [pal565[px] for px in
                raw[index * TS * TS : (index + 1) * TS * TS]]
        expected = rgb565(DIGIT_RGB[digit])
        count = tile.count(expected)
        status = "ok"
        if count < MIN_PIXELS:
            status = "FAILED (colour)"
            ok = False
        else:
            shape = check_shape(tile, digit, expected)
            if shape:
                status = "FAILED (%s)" % shape
                ok = False
        print("digit %d -> tile %d: %d pixels of its colour (%s)" %
              (digit, index, count, status))
    if not ok:
        sys.exit("digit tiles do not match the TILE_NUM constants")
    print("all digit tiles match")


if __name__ == "__main__":
    main()